export const events = [
    {
        eventId: "001",
        eventName: "Electroniche",
        eventDate: {prelims: ["April 14, 2023", "April 14, 2023"], finals: "April 15, 2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/electroniche.png",
        eventType: "circuit-robotics",
        eventHashtags: ["Creative", "Circuits"],
        eventCoordinators: ["Arunim Ray [ 9431915874 ]", "Praveen [ 8529772605 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 2,
        maxMembers: 3,
        // eventShortDescription: "An intuition based electronic circuit-building event",
        eventDescription: ["The name of the event derives from the German word ”elektronische” which means electronics. Are you an engineering student who loves electronics? Do you see resistors, capacitors and inductors everywhere? Do you have a passion for analog and digital circuit systems? Then you won't want to miss our upcoming event! We have got you all covered………………………!!", "Tired of Dream Walking everyday into your world of creative ideas? Rise from your grave and conquer the World of Circuits! Channelise your creative ideas and intuitions into designing circuits and show the world what you are made up of!", "Taking a pinch of inspiration from nature itself, Team Srijan, Jadavpur University unveils ELECTRONICHE, our one of its kind Circuit Designing Event. Get Ready to play with a bunch of MOSFETs,Capacitors and what not!!"],
        eventRules: ["UG1, UG2 and UG3 ( team members must be from the same year ) students can participate in this event", "In ROUND 1: We will be having two different sets of question papers. Set-1 for UG1 and Set-2 for UG2 and UG3 (common set for UG2 and UG3).", "For UG1 participants, questions will be comparable to JEE Advanced level. Questions will be mostly based on basic RC and RL circuits.", "For UG2 and UG3 participants, questions will be mostly from analog circuit design, digital circuit design, circuit theory, signals and system.", "The test will be comprising of multiple choice questions(MCQ) and numerical answer type(NAT) questions. Negative marking will be present. Further details regarding the marking  scheme will be mentioned at the time of exam.", "The top 5 teams from UG1 and the top 10 teams from UG2 & UG3 combined.(Restricted to a maximum of 5 UG3 teams) will be eligible for Round-2", "In ROUND 2: This will be an interactive session for the groups. It will be composed of questions which need your intuition and designing skills to be applied. Each group will be given one question and you need to work it out along with the host.", "No need to worry about the difficulty level. The questions will be adapted accordingly for UG1, UG2 and UG3.", "Do bring your own SCRIBBLE PADS and PEN to do the rough work."],
        eventRuleLink: "https://docs.google.com/document/d/1EgT55EllzRdAJP2n9i-pLoD9b0GL0uxLlunEMA2gLvg/edit"
    },
    {
        eventId: "002",
        eventName: "Cypher 3331",
        eventDate: {prelims: ["April 14, 2023"], finals: "April 15, 2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/ctf-01.png",
        eventType: "brainstorming",
        eventHashtags: ["Cybersecurity", "Brainstorming"],
        eventCoordinators: ["Dhritiman Debnath [ 8895522464 ]", "Urwah Jawaid [ 9103158993 ]", "Shuddhasattwa Guha [ 9434660055 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 1,
        maxMembers: 3,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["Unleash the cryptographer in you and join us for an event filled with mystery, challenges, and excitement - Cypher 3331.", " The event will consist of a quick crash course on cryptography, followed by preliminary rounds of five consequent steps of cryptographic problems to uncover the clues and hints of the underlying treasure hunt . The first five teams to complete the prelims within the given time will qualify for the finals, where the challenges will get even more complex and gruelling. The top three teams to complete the final rounds within two hours will be crowned the winners of the event.", "Don't miss out on this exhilarating opportunity to test your cryptography skills and win big!"],
        eventRules: ["Prelims: A team must consist of 1 to 3 members to participate in the event.", "All participants will be given a quick crash course on cryptography.", "The prelims will consist of 5 consecutive steps of cryptographic problems, each providing clues and hints to solve a digital treasure hunt. The problems will be based on the concepts taught in the crash course.", "The time allocation for the prelims is 1.5 hours for the crash course and 1 hour for the competition rounds.The first 5 teams to complete the preliminary rounds within the timeslot of the event (1 hour) will qualify for the finals.", "Finals: The final stage will consist of more complex and challenging cryptographic problems, again based on the concepts of the quick course during prelims.", "Fundamental Structure of the finals will remain consistent with that of the prelims, with the exception of a few additional tools being provided to the qualifying five teams to aid in solving the problems.", "The first top 3 teams to complete the final rounds within 2 hours will be declared the winners of the event."],
        eventRuleLink: "https://docs.google.com/document/d/1NYOjy76l8ra13i6isTOSf_AKbpG8RWeXQGALbtFULkE/edit"
    },
    {
        eventId: "003",
        eventName: "Ace the Case",
        eventDate: {prelims: ["April 12, 2023"], finals: "April 14, 2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/Ace-the-Case.png",
        eventType: "business-management",
        eventHashtags: ["Casestudy", "Management"],
        eventCoordinators: ["Abhisikta Joarder [ 8017172282 ]", "Dwaipayan Haldar [ 9674273275 ]", "Sukalyan Bisui [ 8697488984 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 1,
        maxMembers: 3,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["Do you have a knack for solving problems? Or have an itch in the brain when you stumble upon a thought provoking question? Are you open to new ideas?", "Get ready to flex your problem-solving muscles at Ace the Case! Put your critical thinking and analytical skills to the test as you work together in a team to solve real-world problems. Think outside the box,compete against other brilliant minds, learn from each other, but most importantly have fun while doing it.", "Join us for a day of learning and fun to tackle real-world challenges and see who can come up with the most innovative solutions!"],
        eventRules: ["Register in teams of 1-3 members, Prompt will be given 2 days prior", "Strictly adhere to slide limit", "In ROUND 1 : It is the Selection round which will be held in Online mode. Abstract submission within 24hrs of prompt release - 1 slide", "In ROUND 2 : This is the Finale that will be held in Offline mode. Slide limit : 4 + 1 slide(for team name) + 1 slide(concluding slide)", "Pitch time: 4-5 mins", "2 mins rebuttal from judges", "Brownie points for sticking to time limits"],
        eventRuleLink: "https://docs.google.com/document/d/1IKbX3buznPO9Xhdk3C5mVbjrA-BEzCHTQti8zC2WZWA/edit"
    },
    {
        eventId: "004",
        eventName: "The Biznez Plan",
        eventDate: {prelims: ["April 16, 2023"], finals: "April 16, 2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/The-Biznez-Plan.png",
        eventType: "business-management",
        eventHashtags: ["Business", "Planning"],
        eventCoordinators: ["Asmit Acharya [ 9433082213 ]", "Supriti Sarkar [ 6289880272 ]", "Aneesh Gupta [ 7980704792 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 1,
        maxMembers: 3,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["Want to live the Shark Tank life? But the semesters and assignments wouldn't let you? Well, we got you covered.", "Biznez Plan, the flagship B-plan event of Srijan is here for you to make an impact on the society.Be ready to pitch your business ideas in groups constituting 1-3 members ,taking in consideration all the nitty gritties of the corporate and business world and make the most sustainable and profitable business possible.","Disentangle real life problems and scenarios and startle us with your unblemished solutions.Be the entrepreneur you have always aspired to be."],
        eventRules: ["Cross-college teams are allowed. Original ideas are encouraged.", "Each team must register in advance to participate in the competition.", "The use of any unfair means or plagiarism will lead to disqualification.", "The judges' decision will be final and binding.", "Team members: 1 to 3", "Round 1: Prelims","2min of elevator pitch based on a 2slider presentation.","Round 2: Finals", "Top 10 teams qualify for the final round.", "Pitching Time: 5+3mins","Maximum 10 slides permitted(excluding the introduction and conclusion)."],
        eventRuleLink: "https://docs.google.com/document/d/1Eknphe0YYFoI_JnlQkcUmTpNyCFpQTYsfA3ddXKYPP0/edit?usp=sharing"
    },
    {
        eventId: "005",
        eventName: "Boardroom War",
        eventDate: {prelims: ["April 13, 2023 - April 14, 2023"], finals: "April 15, 2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/Boardroom-War.png",
        eventType: "business-management",
        eventHashtags: ["Business", "Meeting"],
        eventCoordinators: ["Debamita Banerjee [ 9163918118 ]", "Sparsh Gupta [ 8100555567 ]", "Harsham Mishra [ 7980623712 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 1,
        maxMembers: 1,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["Being the CEO or a lead investor in a company is a dream many seek - but the job comes with more than just a big paycheck. So before you dive headfirst into the corporate world, get a taste of being at the top with Boardroom War.", "Boardroom War simulates real-life boardroom meetings where you play a key role in a company's top management and battle it out against your peers over concepts such as Mergers & Acquisitions, Expansions, PR debacles and much more. Business acumen isn't all that's going to pull you through either because sometimes - you don't just play the game, you play the man. So have you got what it takes to rise to the ocassion?"],
        eventRules: ["Team Members - Individual Participation", "Round-1: Prelims (Mini Case Study) - Conducted in Online mode. Case would be provided 24 hours before submission.", "Round-2: Finals (Boardroom Meeting) - Prep time after Meeting Agenda Announcement - 1 hour, Meeting Duration - 30 minutes", "Registering in advance is compulsory to participate in the event.", "The Case Study PPT for prelims should not be more than 3 slides.", "The core idea of the event is conflict resolution. Any personal attacks or use of abusive language would be grounds for disqualification.", "The judges' decision will be final and binding."],
        eventRuleLink: "https://docs.google.com/document/d/1fqgwPfcoFKiYUnU9YGhqM3sR-9ubtFqkywXr3LH5I1g/edit"
    },
    {
        eventId: "006",
        eventName: "Ultimate Power Squid Game",
        eventDate: {prelims: ["April 14, 2023"], finals: "April 15, 2023 or April 16, 2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/UPSG.png",
        eventType: "misc",
        eventHashtags: ["Brainstorming", "Circuit"],
        eventCoordinators: ["Ekbal Hossain [ 8207225547 ]", "Dipendu Gupta [ 9007455163 ]", "Sandip Santra [ 6295449062 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 3,
        maxMembers: 5,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: [`How would you like to be Player 456? Gear yourself for the running second season of UlTIMATE POWER SQUID GAME in Srijan, inspired from the famous Netflix series 'Squid Game' (2021). Swerve through a series of 6 levels moulded with engineering, sciences and logic, with "Power" as an engineering concept serving as one of the primary focal points, being punctilious and precise all along the way, and take away the competition and the prizes! Don't worry, we won't kill off the others!!`],
        eventRules: ["3-5 players per team and 6 different levels", "A total of 12 teams will go past through the first round from the total unlimited teams based on their design skills", "The value of points are limited to the specific level and are not carried over", "Teams will not be allowed compensation for time wasting", "A volunteer can disqualify a participant or team for breaking the decorum if deemed viable", "There are total 6 stages in this game.", "Please click upon the 'Click Here' button below to access the UPSG RULE BOOK"],
        eventRuleLink: "https://docs.google.com/presentation/d/1seV_fGmrzPuO3QcC6HuJaTFc96ZTTEd2/edit#slide=id.p1"
    },
    {
        eventId: "007",
        eventName: "Climbon'23",
        eventDate: {prelims: ["April 15, 2023"], finals: "April 16, 2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/CLIMBON.png" ,
        eventType: "misc",
        eventHashtags: ["Mountaineering", "Climbing"],
        eventCoordinators: ["Krishna Mittal  [ 8540062753 ]", "Urwah Jawaid [ 9103158993 ]", "Ashish Kumar Mandal [ 7294925744 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 1,
        maxMembers: 1,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["CLIMBON is an artificial rock climbing competition organized by Jadavpur University Mountaineering And Hiking Club every year. It is open to all and there is no age or gender bar. No prior experience is required. Any passionate person from any college can participate. The competition would take place under the supervision of esteemed instructors and all the safety gears would also be provided. It is the best place for any adventurer to begin."],
        eventRules: ["Climbing routes: The competition may have different climbing routes with varying levels of difficulty, which are marked with colored holds. Climbers must follow the designated route and only use the marked holds. Touching any other part of the wall or using any other holds is not allowed and may result in disqualification.", "Timing: Each climber has a set amount of time to complete the route. The time limit may vary depending on the difficulty level of the route. If the climber does not complete the route within the specified time, their score will be based on the furthest point they reached.", "Scoring: The score is determined by the number of holds the climber reaches and touches during the climb. Climbers are awarded points for each hold they touch. The climber with the highest score in their category wins.","Categories: Climbers may be grouped into different categories based on their gender. Each category may have different routes and scoring criteria.","Safety: Safety is of utmost importance in artificial rock climbing contests. Climbers must follow all safety guidelines and instructions provided by event organizers. Judges may stop a climber's ascent if they feel that the climber is in danger or not following safety rules.","Sportsmanship: Climbers are expected to display good sportsmanship and respect for fellow competitors. Any unsportsmanlike behavior or actions that endanger others may result in disqualification.","Equipment: We will provide all the necessary equipment for the competition, but climbers are encouraged to wear well-fitting shoes with a thin sole and good grip, such as PT shoes."],
        eventRuleLink: "https://drive.google.com/file/d/1LUraTyqbn8HVO2_sKE_Dh7nvUfi_hJas/view"
    },
    {
        eventId: "008",
        eventName: "Bridge the Gap",
        eventDate: {prelims: ["April 14, 2023"], finals: "Not Decided Yet"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/BTG.png" ,
        eventType: "misc",
        eventHashtags: ["Construction", "Civil"],
        eventCoordinators: ["Sk Samiul Hoque  [ 8436384925 ]", "Aritra Show [ 9748945722 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 2,
        maxMembers: 4,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["The Bridge the Gap is a day-long event where teams of a minimum of 2 and a maximum of 4 members would construct a bridge model (cable-stayed) from materials like planks, nails, wires, glue, etc., within the specified time. The final models will be examined by renowned academicians, government officials, and industry experts. They will be tested for deformations using standardized loads and marked on aesthetics, stability, and economic sustainability factors."],
        eventRules: ["Introduction: A cable-stayed bridge is one that is supported by a number of straight cables that go directly to one or more vertical towers. The live load is transferred to the vertical towers by the tensile forces in the cables. The cable forces are transferred to the foundations by the towers through vertical compression, while the deformations of the deck under live loads are decreased to give better stiffness.", "Task: Create a cable-stayed bridge out of wooden planks, popsicle sticks, nails, and steel wires that can withstand a design load while adhering to the design constraints provided by the organizers. The problem statement will include a detailed description of the design load and design constraints.", "Problem Statement: The problem statement will be revealed on the day of the event. At the end of the document, there is an attachment with a pre-event reference drawing. These drawings are only for reference purposes. It is possible that the detailed drawing may differ.", "Team Specifications: A team can have a minimum of 2 and a maximum of 4 members. Students from various educational institutions and departments of any year of study at the Undergraduate level can work together to form a team.", "Judging Criteria: Out of 100 marks the judges (renowned academician, government officials, and industrial experts) will judge the designs based on: Aesthetics: 25, Design: 30, Creativity: 20, Deflection: 20, Economical Design: 5", "Requirements: The participants will be provided with everything from the organizers' end. The teams need to carry only essential stationery items (like Pen, Pencil, and Eraser).", "Please click upon the 'Click Here' button below to access the BRIDGE THE GAP RULE BOOK"],
        eventRuleLink: "https://docs.google.com/document/d/1EWoGi4EknK5TG109Fl6zGstp1Dy73NE6Ns6nRe0Io98/edit"
    },
    {
        eventId: "009",
        eventName: "Smart Traffic Forum",
        eventDate: {prelims: ["April 15, 2023"], finals: "April 15, 2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/STF.png" ,
        eventType: "misc",
        eventHashtags: ["Data Analytics", "Challenges"],
        eventCoordinators: ["Aritro Roy Mitra  [ 7044634674 ]", "Uttarayan Roy [ 8017047670 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 1,
        maxMembers: 2,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["Smart Traffic Forum is a 3hrs. a long event that can have a single participant or a team of a maximum of 2 members would analyze vehicular traffic data in real-time. Finally, the participants need to work on the data to draw summaries, prepare a dashboard, and utilize the engineering mindset to critically comment on the given data set."],
        eventRules: ["No. of team members: 01 (min.) to 02 (max.) Students from various educational institutions and departments of any year of study at the Undergraduate level can work together to form a team. ", "You are given the real field co-ordinates of vehicles in a mixed traffic condition for a merging section (two separate traffic streams join to form a single one) along with some other details (length and width of each vehicle, vehicle id and class, and the timeframe corresponding to that field co-ordinates). Additionally, the gore coordinates shall also be given.", "The data analysis should be measured with respect to the original dataset and can be done in any software of choice, but must be finally presented in an EXCEL file.", "The graphs/dashboarding/plots must be clearly distinguishable and aesthetically appealing", "The approach in calculating the parameters must be logical and if there are any assumptions in doing so, that must be clearly mentioned beforehand", "The inferences drawn from the data analysis must be thought of in terms of improving the traffic flow parameters.", "Please click upon the 'Click Here' button below to access the SMART TRAFFIC FORUM RULE BOOK"],
        eventRuleLink: "https://docs.google.com/document/d/1ArV9vkg6H-UfqNhG29ih4PNj2-FenqLwzZf1JKHy5R4/edit"
    },
    {
        eventId: "010",
        eventName: "Valorant",
        eventDate: {prelims: ["April 14, 2023", "April 15, 2023", "April 16, 2023"], finals: "April 16, 2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/valorant.png" ,
        eventType: "gaming",
        eventHashtags: ["PC", "Gaming"],
        eventCoordinators: ["Arka Sikder [ 7980805318 ]", "Swapnil Saha [ 9123785487 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 5,
        maxMembers: 5,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["A LAN based tournament among 32 Teams to be played. The last Day to Register will be 9th April 11:59 PM."],
        eventRules: ["Teams can’t register and expect to play from outside the gaming premises of JUSL. Physical presence of all the team members in mandatory.", "It is a LAN event and henceforth, the teams are requested to treat it accordingly.", "5 members from each team", "Matches will be played among the 9 maps depending on the ‘Ban and pick’ Method. (Ascent, Bind, Split, Breeze, Fracture, Lotus, Icebox, Haven, Pearl)", "Overtime will be played if a 12-12 score occurs. First Team to win two consecutive round wins.", "In case of an odd number of teams in the semi-final round, the team with the highest score difference (in the semi final round) will get qualified for the finals.", "Headphones, Keyboards, mouse will be provided. But you can bring your own accessories if you want.", "In case of any discrepancy the decision of the coordinators will be considered to be final.", "Please click upon the 'Click Here' button below to access the VALORANT RULE BOOK"],
        eventRuleLink: "https://docs.google.com/document/d/1MuGdQyPaRWjBWwioKPDon0mvbExAc_Favx_CBAX5IxA/edit"
    },
    {
        eventId: "011",
        eventName: "Escape Room",
        eventDate: {prelims: ["April 14, 2023"], finals: "April 15, 2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/EscapeRoom.png" ,
        eventType: "brainstorming",
        eventHashtags: ["Quest", "Puzzle"],
        eventCoordinators: ["Arkojit Sen [ 8768605763 ]", "Jyotishman Sarkar [ 9674318486 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 3,
        maxMembers: 4,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["Escape Room is an enthralling event full of startling questions guaranteed to make one’s mind stumble and stutter, in desperate need of being solved to proceed to the next mind-bender and subsequently through this provocative process,  find one's way out of the labyrinthine paths of the room (no puns intended *wink* *wink*). The fastest 4 teams to ace the prelims will go to the Finals, where even more brutal brainstorming will be expected of them to survive and emerge victorious! Soaring adrenaline levels hand in hand with an ingenious mind is all that is requisite to see the light at the end of the tunnel!"],
        eventRules: ["The event consists of two rounds. Prelims and Finale. The fastest 4 teams finishing the prelims will qualify for the finale.", "Prelims: Each team will have 3-4 members, and they will face an 8x8 matrix full of brainstorming questions.", "Each element of the matrix will have two questions; the answers to the questions will give the row address and column address of the next element. Beware! Don't guess the elements, as you'll be disqualified upon guessing the wrong element! Upon solving each element, your team receives a key. Each key has a part of a jumbled puzzle.", "The goal is to solve the elements one by one, decipher the next location, solve that element, and in this way, collect all four keys, and unscramble the puzzle!", "The first four teams to SUBMIT THE FINAL ANSWER wins, and qualify for the finale.", "Finals: 4 Teams qualify", "Two teams will enter one room together. Look. Understand. Analyse.", "The clue lies right there, everywhere around you, be it the curtain on the floor, or the poster on the wall; they can be anywhere. Decipher the clues chronologically, each clue will lead to the next clue. Points will be given for each clue found for the first time and subsequent clues will hold more points. The numbers put together will give the answer to the combination lock that holds the key to unlock the room. The first team to earn their freedom wins! (In case of no winners, the team with maximum points will win)", "That the questions will be logic, mathematics, and science-based, but nothing out of the blue!"],
        eventRuleLink: "https://docs.google.com/document/d/1aZIh99ggLv_t2-AndWl_QoXs-aQbefqU6QJXSzab9hU/edit"
    },
    {
        eventId: "012",
        eventName: "Homecoming",
        eventDate: {prelims: ["April 14, 2023", "April 15, 2023"], finals: ""},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/homecoming.png" ,
        eventType: "circuit-robotics",
        eventHashtags: ["Maze", "Line-Follower"],
        eventCoordinators: ["Rupayan Pal [ 7439562371 ]", "Sayantan Murmu [ 7599420654 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 1,
        maxMembers: 5,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["I can hardly contain my excitement as I board my flight from Germany to India. It's been years since I've seen my family, and I can't wait to be reunited with them. As I settle into my seat and watch the plane take off, memories of my time in Germany flood my mind. The sights, sounds, and smells of the country are still fresh in my mind, but I'm ready to leave it all behind and embrace the familiar warmth of my homeland.", "Get ready for an exciting and innovative event, Homecoming! Join us for a thrilling line follower bot race where you'll design and build your own bot to follow a path until it reaches the finish line. This competition is open to everyone who loves coding and engineering challenges. Don't miss the chance to showcase your skills and creativity!", "Problem Statement: Build a robot that can trace a complicated network of paths and crossroads, using line following."],
        eventRules: ["Each team may consist of 1-5 members. The team members may be from different colleges.", "Physical damage to the arena or misbehavior with any member of team Srijan is subject to disqualification. The participants can test-run their robots in the arena before each round. However, after the commencement of a round, the participants will not be allowed to make technical changes, such as wiring or code. The decision of the JUSC event officials is final and abiding.", "Event Rules: The evaluation of each robot will be based on points. If the robot crosses a particular segment in the arena, points will be awarded. The robot cannot be adjusted manually, once it takes off from the beginning of a segment.", "If the robot wanders away from the line or gets stuck in the middle of a segment, there are two options - a) Restart from the beginning of the previous segment or b) Skipping to the next segment", "Please click upon the 'Click Here' button below to access the HOMECOMING RULE BOOK"],
        eventRuleLink: "https://docs.google.com/document/d/1qVgofVWyZ6Mm6beBLVjnNr331HorJZme8uF5kgoOKLE/edit"
    },
     {
        eventId: "013",
        eventName: "Cold Case",
        eventDate: {prelims: ["April 14, 2023"], finals: "April 16,2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/coldcase.png" ,
        eventType: "brainstorming",
        eventHashtags: ["Mystery", "Decypher"],
        eventCoordinators: ["Shrobona De [ 9163821724 ]", "Shreyoshi De [ 8961800461 ]","Kaustav Chakraborty [ 8420437800]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 1,
        maxMembers: 1,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["Cold Case is a two-round exciting mystery-solving event in which participants take on the role of investigator. When given a case, they must examine it, comprehend the clues, and crack it with precision and speed.", "A twirling interweb of scenarios and cases which will take you on different roads - Your answers will guide you to the portal of victory, we will always be there with the clues and hints you deserve. No Watsons will be the last man standing, do you have what it takes to conquer this curious game of cat and mouse and bring the victory trophy _holme_? ", "Note: we are expecting to launch a website to gamify the whole event "],
        eventRules: ["It is a solo event where participation shall be on the basis of online registration as well as spot registration.", "No prerequisite skills required.","The event will be held in 2 rounds - Prelims and Finals","Prelims will be held in several slots so students can participate at their preferred time","The slots for prelims will each be of 1 hr and allotment of slots to the participants will be on a first come first serve basis.","Top participants from each slot in the prelims round will qualify for the finals.","For both the rounds, the participants will be presented with a case along with clues using which they have to identify the perpetrator(s). The case will progress stepwise where the participants will be provided with more hints as the case progresses,ultimately leading to a conclusion.","The decision of the organizing committee shall be final and binding. No further queries in this regard shall be entertained."],
        eventRuleLink: "https://drive.google.com/file/d/1YpvsrLYJKWEJMhp8TEJWPy5wr9h5g0b3/view"
    },
     {
        eventId: "014",
        eventName: "Eggs-Plosion",
        eventDate: {prelims: ["April 14, 2023"], finals: "April 16,2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/eggplosion.png" ,
        eventType: "misc",
        eventHashtags: ["Fun", "Egg Drop"],
        eventCoordinators: ["Amaan Ahmed [ 7439525481 ]", "Arghadeep Mukherjee [ 7439693606 ]","Subhodip Das [ 8902678949]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 3,
        maxMembers: 4,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["This is an Egg Drop Challenge planned by Team XLR8 ( JUMSC )"],
        eventRules: ["We plan on providing raw materials to the participating teams", "Raw materials will include everyday items such as eggs, cardboards boxes, cups, plastic plates, paper etc. ","There will be three levels during the testing.","Students are required to build mechanisms which will prevent the egg from breaking when dropped.","This is an on-spot event. Building time for the mechanisms will be disclosed later. Students are required to build the mechanisms in front of the organizing committee."],
        eventRuleLink: "https://docs.google.com/document/d/190L7udpkDvx7gXh7EH9xBHFOxHQ4yjSQU7OyX1OJ40I/edit"
    },
    {
        eventId: "015",
        eventName: "Math-E-Magician",
        eventDate: {prelims: ["April 14, 2023"], finals: "April 16,2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/mathemagician.png" ,
        eventType: "brainstorming",
        eventHashtags: ["Mathematics", "Brainstorming"],
        eventCoordinators: ["Shubhayan Ghosal [ 9903297707 ]", "Subha Bhattacharya [ 9073701438 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 2,
        maxMembers: 3,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["Jadavpur University Mathematical Society (JMS) is a newborn Society of the University. Founded by First Year Undergraduates of the Department Of Mathematics, JU in Jan 2023, it is collaborating with Srijan 2023. Its Unique-ness has no Bound ! Not only of the University, but it is the Nation’s First In-ternational Society consisting of Profs/Students/Research Scholars from various disciplines like Math/Phy/Chem/Eco/Computer/Engg Sciences for the Culti-vation of Pure and applied Mathematics.","Srijan, on the other hand is the AnnuaL Techfest of JU, which was started back in 2007. The Collaboration of the new and the old will seriously yield some beautiful results!","Mathematics has always been a subject of Abstract Logic and A way o ex-plore the intricacies of the order of the Universe.To implement and incorporate thus abstract logic into everyday life for the welfare of human beings is the goal of technology. In this celebration of technology we are hosting an olympiad for students including questions from basic cryptography, puzzles, calculus and a whole lot of analytical skills.There will be only one correct option and no issue of ambiguity.","After those qualifying this event, a seminar will be held where students will present how to represent Mathematical Ideas applied in Technology or some real Engineering or Business Sciences. Application to basic sciences are also invited. But Pure math seminars are strongly discouraged as we cant compare between the both.For help and refernce, we suggest the readers to read the book","MATHEMATICS AND TECHNOLOGY BY C.ROUSSEAU AND Y.SAUBIN , SPRINGER VERLAG,NEW YORK.","As it has been already told, there will be 2 events in the MATH-E-MAGICIAN. Prelims will consist of a Terrific Brainstorming Math Olympiad and the Fi-nals will be consisting of a Math Seminar to be organized by Finalists grouped in appropriate teams on the APPLICATIONS OF MATHEMATICS IN YOUR FAVOURITE ENGINEERING SCIENCE, we frame the follow-ing rules in our RULES DOCUMENT.","Everyone will be provided Certificate of Appreciation , Achieve-ment in Prelims(those who qualify) and Certificate of Merit to the top 3 Finalists ! Because, We Care for your CV/Resume. Also, Top performers will get an Exciting prize !!!"],
        eventRules: ["As it has been already told, there will be 2 events that Prelims will consist of a Terrific Brainstorming Math Olympiad and the Finals will be consisting of a Math Seminar to be organized by Finalists grouped in appropriate teams on the APPLICATIONS OF MATHEMATICS IN YOUR FAVOURITE ENGINEERING SCIENCE, we frame the following rules.", "PRELIMS OLYMPIAD There will be 25 questions,and a 90 minutes and Max Marks 100 time will be provided. Correct answer will be rewarded with a 4 pointer boost, Unanswered will fetch 1. 0 in all other cases. Questions will be of standard type and an candidates are required to fill the answers in the Response sheet to be provided. Candidates should not scribble the answers answers nor correct a previously filled response. They Can use a pencil to fill first for safety but scribbled or recorrected answers will be not be evaluated. ","FINALS Cut off marks for the Olympiad will be soon released. Short listed candidates will be grouped accordingly to present a seminar on the ap-plication of a mathematical topic in any discipline of technology. Candi-dates should present only MS PowerPoint/Overleaf LaTex Presentations and will be judged by a set of experts (who are professionally Research Scholars in Mathematics or Engineering Sciences). A sharp 20 minutes time will be provided. Decisions of Judges will be final and non challenge-able.","Everyone will be provided Certificate of Appreciation , Achieve-ment in Prelims(those who qualify) and Certificate of Merit to the top 3 Finalists ! Because, We Care for your CV/Resume."],
        eventRuleLink: "https://drive.google.com/file/d/1pN0rF7FCuHBLePTTWWz5eOioROWZ3Fkl/view"
    },
    {
        eventId: "016",
        eventName: "Water-Chute",
        eventDate: {prelims: ["April 14, 2023"], finals: "April 16,2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/WaterChute.png" ,
        eventType: "misc",
        eventHashtags: ["Fun", "Brainstorming"],
        eventCoordinators: ["Srinjoy Das [ 9007992609 ]", "Tridibesh Chattoraj [ 8240093146 ]", "Soutrik Nag [ 9330266360 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 2,
        maxMembers: 3,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
        eventDescription: ["Do you remember the good old days when you used to watch people in Discovery Science make cool gadgets like homemade rockets? You were thrilled to see it, right? Why not recreate that thrill again?", "Stratosphere, Jadavpur University Aerospace Club introduces “Water-Chute”, a contest where you get an opportunity to showcase your engineering skills by making a water rocket using bottles and collections of valves and gaskets.", "So, are you ready to build the one that flies the greatest distance?"],
        eventRules: ["TEAM SIZE:  2-3 (Cross-year teams are allowed)", "Materials: Two-liter plastic bottles, Tape-any kind; NO GLUE of any kind, Paper or plastic sheet material such as cardboard, Styrofoam, thin plastic sheet, etc.", "Construction Rules: Rockets must be built by the participating students using only the above listed materials.", "Only one two-liter bottle may be filled with water and pressurized. The pressurized bottle itself must not be modified structurally. Additions to the bottle (such as fins, nose cone, etc.) may be attached using ONLY tape.", "Paint or decorations on the plastic of the pressurized bottles are prohibited. Only tape, paper and plastic may be in direct contact with the pressurized bottle. Tape covering the bottle and other parts of the rocket may be painted or otherwise decorated.", "The mouth of the pressurized bottle must fit over a half-inch schedule 40 PVC pipe(standard 2 lit bottle mouth).", "Additional two 2-liter bottles(maximum) may be cut and added to the pressurized bottle.", "Fins must not interfere with the mouth of the pressurized bottle so that it can fit on the launcher.", "Competition Rules: The competitors add the desired amount of water to their rockets prior to being pressurized. If over-pressurized bottles fail during launch there will be no other chance given to the competitors & 0 point will be rewarded to the chance.", "Competitors select the desired launch angle.", "Participants will get only 2 chances in Prelims & 3 chances in Finals. Best of the chances will be considered as final mark.", "Rockets considered unsafe to launch by the judges will be disqualified.", "The distance from the launcher to the closest part (possibly detached) of the fully-at-rest rocket is measured by the judges.", "Participants can modify their rockets but the rocket should remain same during prelims and finals. If a different rocket is used then the team will be disqualified.", "There will be a Preliminary round and Finals. Top 5 teams will proceed to finals.", "Scoring system in finals = (0.25*Prelims + 0.75* Finals). Awards for the longest distances. Ties are broken by the following criteria, in order:  rocket weight (lighter is favored), average of the 2 runs. Top 3 teams will receive certificates and prizes."],
        eventRuleLink: "https://docs.google.com/document/d/1PyU5Iz36MOMIKz3SudzOhLfDm_-vqqev/edit"
    },

    
  //  {
  //      eventId: "015",
  //      eventName: "Pixellense",
  //      eventDate: {prelims: ["April 13, 2023"], finals: "April 16,2023"},
  //      eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
  //      eventPoster: "/assets/events/Pixellense.png" ,
  //      eventType: "misc",
  //      eventHashtags: ["Photography", "Challenges"],
  //      eventCoordinators: ["Mrinmay Tarafdar [ 9749386827 ]", "Tanmay Dutt [ 7384884809 ]","Debjit Patar [ 7699914310]"],
  //       eventVenue: "SMCC - 4th Floor - Lab",
  //      minMembers: 1,
  //      maxMembers: 1,
 //        eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
 //       eventDescription: ["Attention all ShutterBUGS! Get ready to showcase your diverse visions and unique perspectives through the lens of your camera . ","Pixellense is an event where you capture unexpected, and thrilling memories through the lens of the camera and aims to recognize, celebrate, and honour the artistic views of the photographers.","So, what are you waiting for? Grab your camera and start capturing those amazing shots. We can't wait to see what you come up with!"],
  //      eventRules: ["1.Photographs can be clicked using any device (mobile, DSLR. etc.) The theme for the photograph will be given on the event day (13th), at 10 a.m. Participants have to click photographs relevant to the given theme. ", "2. All photographs MUST be clicked on the event day, inside Jadavpur University. Salt Lake campus. Pictures clicked must be of the campus and not outside.","3. There should be only one submission per participant. All the photographs should be emailed to pixellense.srijan23@gmail.com from 9 p.m. of 13th April to 15th April, 9 a.m. ","4. Top 60 photographs will be chosen by our judge by 15th April 12 noon and they will be printed and displayed in the exhibition area by 2 p.m ","5.Each photograph will have a serial number written on it. A voting QR will be placed outside the exhibition area, where people can vote for the best picture by typing in the respective serial number. One person will be allowed only one vote.","6. Voting will be closed at 4 pm, 16th April","7.A weightage of 50% to votes and 50% to the judges' scores will be considered for calculating the final score for the top 60 photographs","8.Top 3 winners will be decided on the basis of the total score. A special mention certificate will be given to the people's winner and judge's winner (if different)."],
  //      eventRuleLink: "https://docs.google.com/document/d/1yMc89cX7krTJhGgDOSulesE_83FFdLGqGW_NhaLtEz4/edit"
   // },
       // {
       // eventId: "011",
       // eventName: "FIFA",
        //eventDate: {prelims: ["April 14, 2023", "April 15, 2023", "April 16, 2023"], finals: "April 16, 2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        //eventPoster: "/assets/events/fifa23.png" ,
        //eventType: "gaming",
        //eventHashtags: ["PC", "Gaming"],
        //eventCoordinators: ["Swapnil Saha [ 9123785487 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
       // minMembers: 5,
       // maxMembers: 5,
        // eventShortDescription: "Deciphering their way through clues and challenges set in the world of binary, the fastest team to the Treasure wins",
       // eventDescription: ["A LAN based tournament among 32 Teams to be played. The last Day to Register will be 9th April 11:59 PM."],
        //eventRules: ["Teams can’t register and expect to play from outside the gaming premises of JUSL. Physical presence of all the team members in mandatory.", "It is a LAN event and henceforth, the teams are requested to treat it accordingly.", "5 members from each team", "Matches will be played among the 9 maps depending on the ‘Ban and pick’ Method. (Ascent, Bind, Split, Breeze, Fracture, Lotus, Icebox, Haven, Pearl)", "Overtime will be played if a 12-12 score occurs. First Team to win two consecutive round wins.", "In case of an odd number of teams in the semi-final round, the team with the highest score difference (in the semi final round) will get qualified for the finals.", "Headphones, Keyboards, mouse will be provided. But you can bring your own accessories if you want.", "In case of any discrepancy the decision of the coordinators will be considered to be final.", "Please click upon the 'Click Here' button below to access the VALORANT RULE BOOK"],
        //eventRuleLink: "https://docs.google.com/document/d/1MuGdQyPaRWjBWwioKPDon0mvbExAc_Favx_CBAX5IxA/edit"
    //},
    
    // {
    //     eventId: "015",
    //     eventName: "Cold Case",
    //     eventDate: {prelims: ["April 14, 2023"], finals: "April 15, 2023"},
    //     // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
    //     eventPoster: "/assets/events/cold-case.jpg",
    //     eventType: "coding",
    //     eventHashtags: ["Mystery", "Open to All"],
    //     eventCoordinators: ["Shrobona De [ 9163821724 ]", "Shreyoshi De [ 8961800461 ]", "Kaustav Chakraborty [ 8420437893 ]"],
    //     // eventVenue: "SMCC - 4th Floor - Lab",
    //     eventShortDescription: "A murder-mystery solving event",
    //     eventDescription: ["Cold Case is a two-round exciting mystery-solving event in which participants take on the role of investigator. When given a case, they must examine it, comprehend the clues, and crack it with precision and speed.", "At each stage, participants must solve a number of fascinating and tough puzzles, much like a sleuth, putting their wit to the test. Similar to a game, each phase will lead to the next, eventually leading the participant to a conclusion. This time, we are expecting to launch a website to gamify the whole event."],
    //     eventRules: ["It is a solo event where participation shall be on the basis of online registration as well as spot registration.", "No prerequisite skills required.", "The event will be held in 2 rounds- Prelims and Finals", "Prelims will be held in several slots so students can participate at their preferred time.", "The slots for prelims will each be of 1 hr and allotment of slots to the participants will be on a first come first serve basis.", "Top participants from each slot in the prelims round will qualify for the finals.", "For both the rounds, the participants will be presented with a case along with clues using which they have to identify the perpetrator(s).The case will progress stepwise where the participants will be provided with more hints as the case progresses,ultimately leading to a conclusion.", "The decision of the organizing committee shall be final and binding. No further queries in this regard shall be entertained."],
    // },
]
