export const events = [
    {
        eventId: "001",
        eventName: "Pass The Baton",
        eventDate: {prelims: ["April 15, 2023"], finals: "April 16, 2023"},
        eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventInterested: "303",
        eventRegistered: "201",
        eventPoster: "/assets/events/pass-the-baton.jpg",
        eventType: "coding",
        eventHashtags: ["Coding Event", "Open to All"],
        eventCoordinators: ["Ayush", "Priyam"],
        eventVenue: "SMCC - 4th Floor - Lab"
    },
    {
        eventId: "002",
        eventName: "Mobilewalla Hackathon",
        eventDate: {fullday: "April 14, 2023"},
        eventTime: {fullday: "10AM - 7PM"},
        eventInterested: "510",
        eventRegistered: "296",
        eventPoster: "/assets/events/mobilewalla-hackathon.jpg",
        eventType: "coding",
        eventHashtags: ["Hackathon", "Open to All"],
        eventCoordinators: ["Ritwick", "Sayak"],
        eventVenue: "SMCC - 2nd Floor - Exam Room"
    },
    {
        eventId: "003",
        eventName: "H42",
        eventDate: {prelims: ["April 20, 2023"], finals: "April 17, 2023"},
        eventTime: {prelims: ["1pm - 4pm"], finals: "10:30AM - 2PM"},
        eventInterested: "206",
        eventRegistered: "165",
        eventPoster: "/assets/events/h42.jpg",
        eventType: "coding",
        eventHashtags: ["Coding Event", "CP Lovers"],
        eventCoordinators: ["Faiz", "Pranav", "Zaid"],
        eventVenue: "SMCC - 4th Floor - Lab"
    },
    {
        eventId: "004",
        eventName: "Sherlocked",
        eventDate: {prelims: ["April 15, 2023", "April 16, 2023"], finals: "April 17, 2023"},
        eventTime: {prelims: ["3pm - 5pm", "11AM - 1PM"], finals: "2:30PM - 5PM"},
        eventInterested: "545",
        eventRegistered: "350",
        eventPoster: "/assets/events/sherlocked.jpg",
        eventType: "coding",
        eventHashtags: ["Coding Event", "Case Solving"],
        eventCoordinators: ["Lakhsya", "Archit", "Ishita"],
        eventVenue: "SMCC - 4th Floor - Lab"
    },
    {
        eventId: "005",
        eventName: "Valorant",
        eventDate: {prelims: ["April 15, 2023", "April 16, 2023"], finals: "April 17, 2023"},
        eventTime: {prelims: ["11AM - 5PM", "11AM - 5PM"], finals: "11PM - 5PM"},
        eventInterested: "820",
        eventRegistered: "460",
        eventPoster: "/assets/events/valorant.jpg",
        eventType: "gaming",
        eventHashtags: ["Gaming Event", "Progamers"],
        eventCoordinators: ["Jatin", "Soham"],
        eventVenue: "JUSL Common Room"
    },
    {
        eventId: "006",
        eventName: "Fifa",
        eventDate: {prelims: ["April 15, 2023", "April 16, 2023"], finals: "April 17, 2023"},
        eventTime: {prelims: ["11AM - 5PM", "11AM - 5PM"], finals: "11PM - 5PM"},
        eventInterested: "850",
        eventRegistered: "560",
        eventPoster: "/assets/events/fifa.jpg",
        eventType: "gaming",
        eventHashtags: ["Gaming Event", "E-sports"],
        eventCoordinators: ["Rupayan", "Abhishek"],
        eventVenue: "JUSL Common Room"
    },
    {
        eventId: "007",
        eventName: "Rocket League",
        eventDate: {prelims: ["April 15, 2023", "April 16, 2023"], finals: "April 17, 2023"},
        eventTime: {prelims: ["11AM - 5PM", "11AM - 5PM"], finals: "11PM - 5PM"},
        eventInterested: "1219",
        eventRegistered: "895",
        eventPoster: "/assets/events/rocket-league.jpg",
        eventType: "gaming",
        eventHashtags: ["Gaming Event", "E-sports"],
        eventCoordinators: ["Tajendra", "Mayank", "Pulkit"],
        eventVenue: "Outside JUSL Boys Hostel"
    },
    {
        eventId: "008",
        eventName: "Climbon'23",
        eventDate: {prelims: ["April 16, 2023"], finals: "April 17, 2023"},
        eventTime: {prelims: ["11AM - 5PM"], finals: "11PM - 4PM"},
        eventInterested: "449",
        eventRegistered: "235",
        eventPoster: "/assets/events/climbon.jpg",
        eventType: "gaming",
        eventHashtags: ["Gaming Event", "sports"],
        eventCoordinators: ["Aryan", "Aditya Anand"],
        eventVenue: "Artificial Rock Climbing Area"
    },
    {
        eventId: "009",
        eventName: "The Biznez Plan",
        eventDate: {prelims: ["April 15, 2023"], finals: "April 16, 2023"},
        eventTime: {prelims: ["11AM - 4PM"], finals: "2PM - 5PM"},
        eventInterested: "420",
        eventRegistered: "265",
        eventPoster: "/assets/events/biznez-plan.jpg",
        eventType: "business-management",
        eventHashtags: ["Business", "Management"],
        eventCoordinators: ["Mehedi", "Sourodeep", "Aditya"],
        // eventVenue: {mentorship: "IEE - 2nd Floor - Btech", finals: "Power - 2nd Floor - Seminar Hall"}
        eventVenue: "IEE - 2nd Floor - Btech"
    },
    {
        eventId: "010",
        eventName: "Mindspark",
        eventDate: {prelims: ["April 16, 2023"], finals: "April 17, 2023"},
        eventTime: {prelims: ["11AM - 5PM"], finals: "11AM - 4PM"},
        eventInterested: "440",
        eventRegistered: "285",
        eventPoster: "/assets/events/mindspark.jpg",
        eventType: "brainstorming",
        eventHashtags: ["Brainstorming", "Braingames"],
        eventCoordinators: ["Sabu", "Divyanshu", "Sohaib"],
        eventVenue: "IEE - 4th Floor - 2nd Year"
    },
    {
        eventId: "011",
        eventName: "Rook 'N Roll",
        eventDate: {prelims: ["April 15, 2023"], finals: "April 16, 2023"},
        eventTime: {prelims: ["11AM - 5PM"], finals: "11AM - 2PM"},
        eventInterested: "490",
        eventRegistered: "325",
        eventPoster: "/assets/events/rook-n-roll.jpg",
        eventType: "brainstorming",
        eventHashtags: ["Brainstorming", "Braingames"],
        eventCoordinators: ["Diyasha", "Mihir", "Hirak"],
        eventVenue: "IEE - 4th Floor - 3rd Year"
    },
    {
        eventId: "012",
        eventName: "Electroniche",
        eventDate: {prelims: ["April 15, 2023"], finals: "April 16, 2023"},
        eventTime: {prelims: ["11AM - 5PM"], finals: "11AM - 4PM"},
        eventInterested: "460",
        eventRegistered: "225",
        eventPoster: "/assets/events/electroniche.jpg",
        eventType: "brainstorming",
        eventHashtags: ["Brainstorming", "Braingames"],
        eventCoordinators: ["Saptarshi", "Jayant", "Nilanjan"],
        eventVenue: "IEE - 5th Floor - 4th Year"
    },
    {
        eventId: "013",
        eventName: "Math-E-Magician",
        eventDate: {prelims: ["April 15, 2023"], finals: "April 16, 2023"},
        eventTime: {prelims: ["11AM - 5PM"], finals: "11AM - 4PM"},
        eventInterested: "489",
        eventRegistered: "336",
        eventPoster: "/assets/events/math-e-magician.jpg",
        eventType: "brainstorming",
        eventHashtags: ["Brainstorming", "Braingames"],
        eventCoordinators: ["Priyatam", "Ayush Pareek"],
        eventVenue: "Construction - 2nd Floor - 1st Year"
    },
    {
        eventId: "014",
        eventName: "Escape Room",
        eventDate: {prelims: ["April 15, 2023", "April 16, 2023"], finals: "April 17, 2023"},
        eventTime: {prelims: ["11AM - 5PM", "11Am - 5PM"], finals: "11AM - 4PM"},
        eventInterested: "236",
        eventRegistered: "120",
        eventPoster: "/assets/events/escape-room.jpg",
        eventType: "brainstorming",
        eventHashtags: ["Brainstorming", "Braingames"],
        eventCoordinators: ["Shreyashi", "Elina", "Anushka", "Arkojit"],
        eventVenue: "IEE - 2nd Floor - 1st Year"
    },
    {
        eventId: "015",
        eventName: "Cold Case",
        eventDate: {prelims: ["April 16, 2023"], finals: "April 17, 2023"},
        eventTime: {prelims: ["11AM - 5PM"], finals: "11AM - 4PM"},
        eventInterested: "546",
        eventRegistered: "470",
        eventPoster: "/assets/events/cold-case.jpg",
        eventType: "brainstorming",
        eventHashtags: ["Brainstorming", "Braingames"],
        eventCoordinators: ["Shrobona", "Shreyashi"],
        eventVenue: "IEE - 3rd Floor - Seminar Hall"
    },
]