export const events = [
    {
        eventId: "001",
        eventName: "Electroniche",
        eventDate: {prelims: ["April 14, 2023", "April 14, 2023"], finals: "April 15, 2023"},
        // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
        eventPoster: "/assets/events/electroniche.png",
        eventType: "circuit-robotics",
        eventHashtags: ["Creative", "Open for All"],
        eventCoordinators: ["Arunim Ray [ 9431915874 ]", "Praveen [ 8529772605 ]"],
        // eventVenue: "SMCC - 4th Floor - Lab",
        minMembers: 2,
        maxMembers: 3,
        // eventShortDescription: "An intuition based electronic circuit-building event",
        eventDescription: ["The name of the event derives from the German word ”elektronische” which means electronics. Are you an engineering student who loves electronics? Do you see resistors, capacitors and inductors everywhere? Do you have a passion for analog and digital circuit systems? Then you won't want to miss our upcoming event! We have got you all covered………………………!!", "Tired of Dream Walking everyday into your world of creative ideas? Rise from your grave and conquer the World of Circuits! Channelise your creative ideas and intuitions into designing circuits and show the world what you are made up of!", "Taking a pinch of inspiration from nature itself, Team Srijan, Jadavpur University unveils ELECTRONICHE, our one of its kind Circuit Designing Event. Get Ready to play with a bunch of MOSFETs,Capacitors and what not!!"],
        eventRules: ["UG1, UG2 and UG3 ( team members must be from the same year ) students can participate in this event", "In ROUND 1: We will be having two different sets of question papers. Set-1 for UG1 and Set-2 for UG2 and UG3 (common set for UG2 and UG3).", "For UG1 participants, questions will be comparable to JEE Advanced level. Questions will be mostly based on basic RC and RL circuits.", "For UG2 and UG3 participants, questions will be mostly from analog circuit design, digital circuit design, circuit theory, signals and system.", "The test will be comprising of multiple choice questions(MCQ) and numerical answer type(NAT) questions. Negative marking will be present. Further details regarding the marking  scheme will be mentioned at the time of exam.", "The top 5 teams from UG1 and the top 10 teams from UG2 & UG3 combined.(Restricted to a maximum of 5 UG3 teams) will be eligible for Round-2", "In ROUND 2: This will be an interactive session for the groups. It will be composed of questions which need your intuition and designing skills to be applied. Each group will be given one question and you need to work it out along with the host.", "No need to worry about the difficulty level. The questions will be adapted accordingly for UG1, UG2 and UG3.", "Do bring your own SCRIBBLE PADS and PEN to do the rough work."],
        eventRuleLink: "https://docs.google.com/document/d/1EgT55EllzRdAJP2n9i-pLoD9b0GL0uxLlunEMA2gLvg/edit"
    },
    // {
    //     eventId: "015",
    //     eventName: "Cold Case",
    //     eventDate: {prelims: ["April 14, 2023"], finals: "April 15, 2023"},
    //     // eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
    //     eventPoster: "/assets/events/cold-case.jpg",
    //     eventType: "coding",
    //     eventHashtags: ["Mystery", "Open to All"],
    //     eventCoordinators: ["Shrobona De [ 9163821724 ]", "Shreyoshi De [ 8961800461 ]", "Kaustav Chakraborty [ 8420437893 ]"],
    //     // eventVenue: "SMCC - 4th Floor - Lab",
    //     eventShortDescription: "A murder-mystery solving event",
    //     eventDescription: ["Cold Case is a two-round exciting mystery-solving event in which participants take on the role of investigator. When given a case, they must examine it, comprehend the clues, and crack it with precision and speed.", "At each stage, participants must solve a number of fascinating and tough puzzles, much like a sleuth, putting their wit to the test. Similar to a game, each phase will lead to the next, eventually leading the participant to a conclusion. This time, we are expecting to launch a website to gamify the whole event."],
    //     eventRules: ["It is a solo event where participation shall be on the basis of online registration as well as spot registration.", "No prerequisite skills required.", "The event will be held in 2 rounds- Prelims and Finals", "Prelims will be held in several slots so students can participate at their preferred time.", "The slots for prelims will each be of 1 hr and allotment of slots to the participants will be on a first come first serve basis.", "Top participants from each slot in the prelims round will qualify for the finals.", "For both the rounds, the participants will be presented with a case along with clues using which they have to identify the perpetrator(s).The case will progress stepwise where the participants will be provided with more hints as the case progresses,ultimately leading to a conclusion.", "The decision of the organizing committee shall be final and binding. No further queries in this regard shall be entertained."],
    // },
    // {
    //     eventId: "001",
    //     eventName: "Pass The Baton",
    //     eventDate: {prelims: ["April 15, 2023"], finals: "April 16, 2023"},
    //     eventTime: {prelims: ["10:30AM - 4PM"], finals: "2PM - 5PM"},
    //     eventPoster: "/assets/events/pass-the-baton.jpg",
    //     eventType: "coding",
    //     eventHashtags: ["Coding Event", "Open to All"],
    //     eventCoordinators: ["Ayush", "Priyam"],
    //     eventVenue: "SMCC - 4th Floor - Lab",
    // },
    // {
    //     eventId: "002",
    //     eventName: "Mobilewalla Hackathon",
    //     eventDate: {fullday: "April 14, 2023"},
    //     eventTime: {fullday: "10AM - 7PM"},
    //     eventInterested: "510",
    //     eventRegistered: "296",
    //     eventPoster: "/assets/events/mobilewalla-hackathon.jpg",
    //     eventType: "coding",
    //     eventHashtags: ["Hackathon", "Open to All"],
    //     eventCoordinators: ["Ritwick", "Sayak"],
    //     eventVenue: "SMCC - 2nd Floor - Exam Room"
    // },
    // {
    //     eventId: "003",
    //     eventName: "H42",
    //     eventDate: {prelims: ["April 20, 2023"], finals: "April 17, 2023"},
    //     eventTime: {prelims: ["1pm - 4pm"], finals: "10:30AM - 2PM"},
    //     eventInterested: "206",
    //     eventRegistered: "165",
    //     eventPoster: "/assets/events/h42.jpg",
    //     eventType: "coding",
    //     eventHashtags: ["Coding Event", "CP Lovers"],
    //     eventCoordinators: ["Faiz", "Pranav", "Zaid"],
    //     eventVenue: "SMCC - 4th Floor - Lab"
    // },
    // {
    //     eventId: "004",
    //     eventName: "Sherlocked",
    //     eventDate: {prelims: ["April 15, 2023", "April 16, 2023"], finals: "April 17, 2023"},
    //     eventTime: {prelims: ["3pm - 5pm", "11AM - 1PM"], finals: "2:30PM - 5PM"},
    //     eventInterested: "545",
    //     eventRegistered: "350",
    //     eventPoster: "/assets/events/sherlocked.jpg",
    //     eventType: "coding",
    //     eventHashtags: ["Coding Event", "Case Solving"],
    //     eventCoordinators: ["Lakhsya", "Archit", "Ishita"],
    //     eventVenue: "SMCC - 4th Floor - Lab"
    // },
    // {
    //     eventId: "005",
    //     eventName: "Valorant",
    //     eventDate: {prelims: ["April 15, 2023", "April 16, 2023"], finals: "April 17, 2023"},
    //     eventTime: {prelims: ["11AM - 5PM", "11AM - 5PM"], finals: "11PM - 5PM"},
    //     eventInterested: "820",
    //     eventRegistered: "460",
    //     eventPoster: "/assets/events/valorant.jpg",
    //     eventType: "gaming",
    //     eventHashtags: ["Gaming Event", "Progamers"],
    //     eventCoordinators: ["Jatin", "Soham"],
    //     eventVenue: "JUSL Common Room"
    // },
    // {
    //     eventId: "006",
    //     eventName: "Fifa",
    //     eventDate: {prelims: ["April 15, 2023", "April 16, 2023"], finals: "April 17, 2023"},
    //     eventTime: {prelims: ["11AM - 5PM", "11AM - 5PM"], finals: "11PM - 5PM"},
    //     eventInterested: "850",
    //     eventRegistered: "560",
    //     eventPoster: "/assets/events/fifa.jpg",
    //     eventType: "gaming",
    //     eventHashtags: ["Gaming Event", "E-sports"],
    //     eventCoordinators: ["Rupayan", "Abhishek"],
    //     eventVenue: "JUSL Common Room"
    // },
    // {
    //     eventId: "007",
    //     eventName: "Rocket League",
    //     eventDate: {prelims: ["April 15, 2023", "April 16, 2023"], finals: "April 17, 2023"},
    //     eventTime: {prelims: ["11AM - 5PM", "11AM - 5PM"], finals: "11PM - 5PM"},
    //     eventInterested: "1219",
    //     eventRegistered: "895",
    //     eventPoster: "/assets/events/rocket-league.jpg",
    //     eventType: "gaming",
    //     eventHashtags: ["Gaming Event", "E-sports"],
    //     eventCoordinators: ["Tajendra", "Mayank", "Pulkit"],
    //     eventVenue: "Outside JUSL Boys Hostel"
    // },
    // {
    //     eventId: "008",
    //     eventName: "Climbon'23",
    //     eventDate: {prelims: ["April 16, 2023"], finals: "April 17, 2023"},
    //     eventTime: {prelims: ["11AM - 5PM"], finals: "11PM - 4PM"},
    //     eventInterested: "449",
    //     eventRegistered: "235",
    //     eventPoster: "/assets/events/climbon.jpg",
    //     eventType: "gaming",
    //     eventHashtags: ["Gaming Event", "sports"],
    //     eventCoordinators: ["Aryan", "Aditya Anand"],
    //     eventVenue: "Artificial Rock Climbing Area"
    // },
    // {
    //     eventId: "009",
    //     eventName: "The Biznez Plan",
    //     eventDate: {prelims: ["April 15, 2023"], finals: "April 16, 2023"},
    //     eventTime: {prelims: ["11AM - 4PM"], finals: "2PM - 5PM"},
    //     eventInterested: "420",
    //     eventRegistered: "265",
    //     eventPoster: "/assets/events/biznez-plan.jpg",
    //     eventType: "business-management",
    //     eventHashtags: ["Business", "Management"],
    //     eventCoordinators: ["Mehedi", "Sourodeep", "Aditya"],
    //     // eventVenue: {mentorship: "IEE - 2nd Floor - Btech", finals: "Power - 2nd Floor - Seminar Hall"}
    //     eventVenue: "IEE - 2nd Floor - Btech"
    // },
    // {
    //     eventId: "010",
    //     eventName: "Mindspark",
    //     eventDate: {prelims: ["April 16, 2023"], finals: "April 17, 2023"},
    //     eventTime: {prelims: ["11AM - 5PM"], finals: "11AM - 4PM"},
    //     eventInterested: "440",
    //     eventRegistered: "285",
    //     eventPoster: "/assets/events/mindspark.jpg",
    //     eventType: "brainstorming",
    //     eventHashtags: ["Brainstorming", "Braingames"],
    //     eventCoordinators: ["Sabu", "Divyanshu", "Sohaib"],
    //     eventVenue: "IEE - 4th Floor - 2nd Year"
    // },
    // {
    //     eventId: "011",
    //     eventName: "Rook 'N Roll",
    //     eventDate: {prelims: ["April 15, 2023"], finals: "April 16, 2023"},
    //     eventTime: {prelims: ["11AM - 5PM"], finals: "11AM - 2PM"},
    //     eventInterested: "490",
    //     eventRegistered: "325",
    //     eventPoster: "/assets/events/rook-n-roll.jpg",
    //     eventType: "brainstorming",
    //     eventHashtags: ["Brainstorming", "Braingames"],
    //     eventCoordinators: ["Diyasha", "Mihir", "Hirak"],
    //     eventVenue: "IEE - 4th Floor - 3rd Year"
    // },
    // {
    //     eventId: "012",
    //     eventName: "Electroniche",
    //     eventDate: {prelims: ["April 15, 2023"], finals: "April 16, 2023"},
    //     eventTime: {prelims: ["11AM - 5PM"], finals: "11AM - 4PM"},
    //     eventInterested: "460",
    //     eventRegistered: "225",
    //     eventPoster: "/assets/events/electroniche.jpg",
    //     eventType: "brainstorming",
    //     eventHashtags: ["Brainstorming", "Braingames"],
    //     eventCoordinators: ["Saptarshi", "Jayant", "Nilanjan"],
    //     eventVenue: "IEE - 5th Floor - 4th Year"
    // },
    // {
    //     eventId: "013",
    //     eventName: "Math-E-Magician",
    //     eventDate: {prelims: ["April 15, 2023"], finals: "April 16, 2023"},
    //     eventTime: {prelims: ["11AM - 5PM"], finals: "11AM - 4PM"},
    //     eventInterested: "489",
    //     eventRegistered: "336",
    //     eventPoster: "/assets/events/math-e-magician.jpg",
    //     eventType: "brainstorming",
    //     eventHashtags: ["Brainstorming", "Braingames"],
    //     eventCoordinators: ["Priyatam", "Ayush Pareek"],
    //     eventVenue: "Construction - 2nd Floor - 1st Year"
    // },
    // {
    //     eventId: "014",
    //     eventName: "Escape Room",
    //     eventDate: {prelims: ["April 15, 2023", "April 16, 2023"], finals: "April 17, 2023"},
    //     eventTime: {prelims: ["11AM - 5PM", "11Am - 5PM"], finals: "11AM - 4PM"},
    //     eventInterested: "236",
    //     eventRegistered: "120",
    //     eventPoster: "/assets/events/escape-room.jpg",
    //     eventType: "brainstorming",
    //     eventHashtags: ["Brainstorming", "Braingames"],
    //     eventCoordinators: ["Shreyashi", "Elina", "Anushka", "Arkojit"],
    //     eventVenue: "IEE - 2nd Floor - 1st Year"
    // },
    // {
    //     eventId: "015",
    //     eventName: "Cold Case",
    //     eventDate: {prelims: ["April 16, 2023"], finals: "April 17, 2023"},
    //     eventTime: {prelims: ["11AM - 5PM"], finals: "11AM - 4PM"},
    //     eventInterested: "546",
    //     eventRegistered: "470",
    //     eventPoster: "/assets/events/cold-case.jpg",
    //     eventType: "brainstorming",
    //     eventHashtags: ["Brainstorming", "Braingames"],
    //     eventCoordinators: ["Shrobona", "Shreyashi"],
    //     eventVenue: "IEE - 3rd Floor - Seminar Hall"
    // },
]